// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_methods
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPnYgHXdCdoJBGPSGvZb7jKIWfdn4pe-M',
    appId: '1:747218037971:web:3c584afee46a997eee7826',
    messagingSenderId: '747218037971',
    projectId: 'glamconnect-4000e',
    authDomain: 'glamconnect-4000e.firebaseapp.com',
    databaseURL: 'https://glamconnect-4000e-default-rtdb.firebaseio.com',
    storageBucket: 'glamconnect-4000e.firebasestorage.app',
    measurementId: 'G-50X5VW40FS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqrPxuImhCjABF_dARY8lAlWVnePr-Jc8',
    appId: '1:747218037971:android:164cd75698a109a8ee7826',
    messagingSenderId: '747218037971',
    projectId: 'glamconnect-4000e',
    databaseURL: 'https://glamconnect-4000e-default-rtdb.firebaseio.com',
    storageBucket: 'glamconnect-4000e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3Dr4r7KHF7XROhTD6j6PykP7qpn-3C2U',
    appId: '1:747218037971:ios:45afdc8df051c7f4ee7826',
    messagingSenderId: '747218037971',
    projectId: 'glamconnect-4000e',
    databaseURL: 'https://glamconnect-4000e-default-rtdb.firebaseio.com',
    storageBucket: 'glamconnect-4000e.firebasestorage.app',
    iosBundleId: 'com.glamconnect.glamConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3Dr4r7KHF7XROhTD6j6PykP7qpn-3C2U',
    appId: '1:747218037971:ios:45afdc8df051c7f4ee7826',
    messagingSenderId: '747218037971',
    projectId: 'glamconnect-4000e',
    databaseURL: 'https://glamconnect-4000e-default-rtdb.firebaseio.com',
    storageBucket: 'glamconnect-4000e.firebasestorage.app',
    iosBundleId: 'com.glamconnect.glamConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPnYgHXdCdoJBGPSGvZb7jKIWfdn4pe-M',
    appId: '1:747218037971:web:f853207e826a2cfcee7826',
    messagingSenderId: '747218037971',
    projectId: 'glamconnect-4000e',
    authDomain: 'glamconnect-4000e.firebaseapp.com',
    databaseURL: 'https://glamconnect-4000e-default-rtdb.firebaseio.com',
    storageBucket: 'glamconnect-4000e.firebasestorage.app',
    measurementId: 'G-H25C5K7Q0W',
  );

}