// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_methods
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3Dr4r7KHF7XROhTD6j6PykP7qpn-3C2U',
    appId: '1:747218037971:web:45afdc8df051c7f4ee7826',
    messagingSenderId: '747218037971',
    projectId: 'glamconnect-4000e',
    authDomain: 'glamconnect-4000e.firebaseapp.com',
    storageBucket: 'glamconnect-4000e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3Dr4r7KHF7XROhTD6j6PykP7qpn-3C2U',
    appId: '1:747218037971:android:45afdc8df051c7f4ee7826',
    messagingSenderId: '747218037971',
    projectId: 'glamconnect-4000e',
    storageBucket: 'glamconnect-4000e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3Dr4r7KHF7XROhTD6j6PykP7qpn-3C2U',
    appId: '1:747218037971:ios:45afdc8df051c7f4ee7826',
    messagingSenderId: '747218037971',
    projectId: 'glamconnect-4000e',
    storageBucket: 'glamconnect-4000e.firebasestorage.app',
    iosBundleId: 'com.glamconnect.glamConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3Dr4r7KHF7XROhTD6j6PykP7qpn-3C2U',
    appId: '1:747218037971:ios:45afdc8df051c7f4ee7826',
    messagingSenderId: '747218037971',
    projectId: 'glamconnect-4000e',
    storageBucket: 'glamconnect-4000e.firebasestorage.app',
    iosBundleId: 'com.glamconnect.glamConnect',
  );
}
